# Generated by Django 3.1.4 on 2021-02-23 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Author name', max_length=20)),
                ('description', models.CharField(help_text='Say something about you', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('report', models.TextField()),
                ('pubdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
