# Generated by Django 3.1.4 on 2021-02-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_author_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appblog.author'),
        ),
    ]
