# Generated by Django 3.1.7 on 2021-02-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0008_auto_20210225_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-name']},
        ),
    ]
