# Generated by Django 3.1.7 on 2021-02-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0009_auto_20210227_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
